//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"fmt"
	"net/http"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for DriftResultVerdict.
const (
	DriftResultVerdictFail    DriftResultVerdict = "fail"
	DriftResultVerdictPass    DriftResultVerdict = "pass"
	DriftResultVerdictPending DriftResultVerdict = "pending"
	DriftResultVerdictWarn    DriftResultVerdict = "warn"
)

// Valid indicates whether the value is a known member of the DriftResultVerdict enum.
func (e DriftResultVerdict) Valid() bool {
	switch e {
	case DriftResultVerdictFail:
		return true
	case DriftResultVerdictPass:
		return true
	case DriftResultVerdictPending:
		return true
	case DriftResultVerdictWarn:
		return true
	default:
		return false
	}
}

// Defines values for ExperimentRunRunType.
const (
	ExperimentRunRunTypeBaseline ExperimentRunRunType = "baseline"
	ExperimentRunRunTypeVariant  ExperimentRunRunType = "variant"
)

// Valid indicates whether the value is a known member of the ExperimentRunRunType enum.
func (e ExperimentRunRunType) Valid() bool {
	switch e {
	case ExperimentRunRunTypeBaseline:
		return true
	case ExperimentRunRunTypeVariant:
		return true
	default:
		return false
	}
}

// Defines values for ToolCaptureRiskClass.
const (
	Destructive ToolCaptureRiskClass = "destructive"
	Read        ToolCaptureRiskClass = "read"
	Write       ToolCaptureRiskClass = "write"
)

// Valid indicates whether the value is a known member of the ToolCaptureRiskClass enum.
func (e ToolCaptureRiskClass) Valid() bool {
	switch e {
	case Destructive:
		return true
	case Read:
		return true
	case Write:
		return true
	default:
		return false
	}
}

// Defines values for ListExperimentsParamsStatus.
const (
	ListExperimentsParamsStatusCancelled ListExperimentsParamsStatus = "cancelled"
	ListExperimentsParamsStatusCompleted ListExperimentsParamsStatus = "completed"
	ListExperimentsParamsStatusFailed    ListExperimentsParamsStatus = "failed"
	ListExperimentsParamsStatusPending   ListExperimentsParamsStatus = "pending"
	ListExperimentsParamsStatusRunning   ListExperimentsParamsStatus = "running"
)

// Valid indicates whether the value is a known member of the ListExperimentsParamsStatus enum.
func (e ListExperimentsParamsStatus) Valid() bool {
	switch e {
	case ListExperimentsParamsStatusCancelled:
		return true
	case ListExperimentsParamsStatusCompleted:
		return true
	case ListExperimentsParamsStatusFailed:
		return true
	case ListExperimentsParamsStatusPending:
		return true
	case ListExperimentsParamsStatusRunning:
		return true
	default:
		return false
	}
}

// AnalysisResult defines model for AnalysisResult.
type AnalysisResult struct {
	BehaviorDiff    *BehaviorDiff    `json:"behaviorDiff,omitempty"`
	FirstDivergence *FirstDivergence `json:"firstDivergence,omitempty"`
	SafetyDiff      *SafetyDiff      `json:"safetyDiff,omitempty"`
}

// Baseline defines model for Baseline.
type Baseline struct {
	CreatedAt   *time.Time `json:"createdAt,omitempty"`
	Description *string    `json:"description,omitempty"`
	Name        *string    `json:"name,omitempty"`
	TraceId     *string    `json:"traceId,omitempty"`
}

// BehaviorDiff defines model for BehaviorDiff.
type BehaviorDiff struct {
	Reason  *string `json:"reason,omitempty"`
	Verdict *string `json:"verdict,omitempty"`
}

// DriftDetails defines model for DriftDetails.
type DriftDetails struct {
	DivergenceStep *int    `json:"divergenceStep,omitempty"`
	Reason         *string `json:"reason,omitempty"`
	RiskEscalation *bool   `json:"riskEscalation,omitempty"`
}

// DriftResult defines model for DriftResult.
type DriftResult struct {
	BaselineTraceId *string             `json:"baselineTraceId,omitempty"`
	CreatedAt       *time.Time          `json:"createdAt,omitempty"`
	Details         *DriftDetails       `json:"details,omitempty"`
	DriftScore      *float32            `json:"driftScore,omitempty"`
	TraceId         *string             `json:"traceId,omitempty"`
	Verdict         *DriftResultVerdict `json:"verdict,omitempty"`
}

// DriftResultVerdict defines model for DriftResult.Verdict.
type DriftResultVerdict string

// Experiment defines model for Experiment.
type Experiment struct {
	BaselineTraceId *string             `json:"baselineTraceId,omitempty"`
	CompletedAt     *time.Time          `json:"completedAt,omitempty"`
	CreatedAt       *time.Time          `json:"createdAt,omitempty"`
	Id              *openapi_types.UUID `json:"id,omitempty"`
	Name            *string             `json:"name,omitempty"`
	Progress        *float32            `json:"progress,omitempty"`
	Status          *string             `json:"status,omitempty"`
	Threshold       *float32            `json:"threshold,omitempty"`
	VariantConfig   *VariantConfig      `json:"variantConfig,omitempty"`
	Verdict         *string             `json:"verdict,omitempty"`
}

// ExperimentDetail defines model for ExperimentDetail.
type ExperimentDetail struct {
	BaselineTraceId *string             `json:"baselineTraceId,omitempty"`
	CompletedAt     *time.Time          `json:"completedAt,omitempty"`
	CreatedAt       *time.Time          `json:"createdAt,omitempty"`
	Id              *openapi_types.UUID `json:"id,omitempty"`
	Name            *string             `json:"name,omitempty"`
	Progress        *float32            `json:"progress,omitempty"`
	Runs            *[]ExperimentRun    `json:"runs,omitempty"`
	Status          *string             `json:"status,omitempty"`
	Threshold       *float32            `json:"threshold,omitempty"`
	VariantConfig   *VariantConfig      `json:"variantConfig,omitempty"`
	Verdict         *string             `json:"verdict,omitempty"`
}

// ExperimentReport defines model for ExperimentReport.
type ExperimentReport struct {
	Analysis        *AnalysisResult     `json:"analysis,omitempty"`
	BaselineTraceId *string             `json:"baselineTraceId,omitempty"`
	Error           *string             `json:"error,omitempty"`
	ExperimentId    *openapi_types.UUID `json:"experimentId,omitempty"`
	LatencyDelta    *int                `json:"latencyDelta,omitempty"`
	Runs            *[]ExperimentRun    `json:"runs,omitempty"`
	SimilarityScore *float32            `json:"similarityScore,omitempty"`
	Status          *string             `json:"status,omitempty"`
	TokenDelta      *int                `json:"tokenDelta,omitempty"`
	Verdict         *string             `json:"verdict,omitempty"`
}

// ExperimentRun defines model for ExperimentRun.
type ExperimentRun struct {
	CreatedAt     *time.Time            `json:"createdAt,omitempty"`
	Error         *string               `json:"error,omitempty"`
	Id            *openapi_types.UUID   `json:"id,omitempty"`
	RunType       *ExperimentRunRunType `json:"runType,omitempty"`
	Status        *string               `json:"status,omitempty"`
	TraceId       *string               `json:"traceId,omitempty"`
	VariantConfig *VariantConfig        `json:"variantConfig,omitempty"`
}

// ExperimentRunRunType defines model for ExperimentRun.RunType.
type ExperimentRunRunType string

// FirstDivergence defines model for FirstDivergence.
type FirstDivergence struct {
	Baseline        *string `json:"baseline,omitempty"`
	BaselineCount   *int    `json:"baselineCount,omitempty"`
	BaselineExcerpt *string `json:"baselineExcerpt,omitempty"`
	BaselineSteps   *int    `json:"baselineSteps,omitempty"`
	StepIndex       *int    `json:"stepIndex,omitempty"`
	ToolIndex       *int    `json:"toolIndex,omitempty"`
	Type            *string `json:"type,omitempty"`
	Variant         *string `json:"variant,omitempty"`
	VariantCount    *int    `json:"variantCount,omitempty"`
	VariantExcerpt  *string `json:"variantExcerpt,omitempty"`
	VariantSteps    *int    `json:"variantSteps,omitempty"`
}

// GateCheckRequest defines model for GateCheckRequest.
type GateCheckRequest struct {
	BaselineTraceId string `json:"baselineTraceId"`
	MaxTokens       *int   `json:"maxTokens,omitempty"`

	// MaxTurns Maximum agent loop turns (overrides server default)
	MaxTurns       *int                  `json:"maxTurns,omitempty"`
	Model          string                `json:"model"`
	Provider       *string               `json:"provider,omitempty"`
	RequestHeaders *ReplayRequestHeaders `json:"requestHeaders,omitempty"`
	Temperature    *float32              `json:"temperature,omitempty"`
	Threshold      *float32              `json:"threshold,omitempty"`
	TopP           *float32              `json:"topP,omitempty"`
}

// GateCheckResponse defines model for GateCheckResponse.
type GateCheckResponse struct {
	ExperimentId *openapi_types.UUID `json:"experimentId,omitempty"`
	Status       *string             `json:"status,omitempty"`
}

// GateStatusResponse defines model for GateStatusResponse.
type GateStatusResponse struct {
	ExperimentId *openapi_types.UUID `json:"experimentId,omitempty"`
	Progress     *float32            `json:"progress,omitempty"`
	Status       *string             `json:"status,omitempty"`
}

// PromptContent defines model for PromptContent.
type PromptContent struct {
	Messages *[]PromptMessage `json:"messages,omitempty"`

	// ToolChoice Arbitrary tool-choice payload captured from the source trace.
	ToolChoice interface{}               `json:"tool_choice,omitempty"`
	Tools      *[]map[string]interface{} `json:"tools,omitempty"`
}

// PromptMessage defines model for PromptMessage.
type PromptMessage struct {
	Content    *string                   `json:"content,omitempty"`
	Name       *string                   `json:"name,omitempty"`
	Role       *string                   `json:"role,omitempty"`
	ToolCallId *string                   `json:"tool_call_id,omitempty"`
	ToolCalls  *[]map[string]interface{} `json:"tool_calls,omitempty"`
}

// ReplayRequestHeaders defines model for ReplayRequestHeaders.
type ReplayRequestHeaders struct {
	FreezeSpanId    *string `json:"freezeSpanId,omitempty"`
	FreezeStepIndex *string `json:"freezeStepIndex,omitempty"`
	FreezeTraceId   *string `json:"freezeTraceId,omitempty"`
}

// SafetyDiff defines model for SafetyDiff.
type SafetyDiff struct {
	BaselineRisk   *string `json:"baselineRisk,omitempty"`
	RiskEscalation *bool   `json:"riskEscalation,omitempty"`
	VariantRisk    *string `json:"variantRisk,omitempty"`
}

// ToolCapture defines model for ToolCapture.
type ToolCapture struct {
	Args      *map[string]interface{} `json:"args,omitempty"`
	Error     *string                 `json:"error,omitempty"`
	LatencyMs *int                    `json:"latencyMs,omitempty"`
	Result    *map[string]interface{} `json:"result,omitempty"`
	RiskClass *ToolCaptureRiskClass   `json:"riskClass,omitempty"`
	StepIndex *int                    `json:"stepIndex,omitempty"`
	ToolName  *string                 `json:"toolName,omitempty"`
}

// ToolCaptureRiskClass defines model for ToolCapture.RiskClass.
type ToolCaptureRiskClass string

// TraceComparison defines model for TraceComparison.
type TraceComparison struct {
	Baseline  *TraceDetail `json:"baseline,omitempty"`
	Candidate *TraceDetail `json:"candidate,omitempty"`
	Diff      *struct {
		DivergenceReason    *string  `json:"divergenceReason,omitempty"`
		DivergenceStepIndex *int     `json:"divergenceStepIndex,omitempty"`
		SimilarityScore     *float32 `json:"similarityScore,omitempty"`
	} `json:"diff,omitempty"`
}

// TraceDetail defines model for TraceDetail.
type TraceDetail struct {
	Steps        *[]TraceStep   `json:"steps,omitempty"`
	ToolCaptures *[]ToolCapture `json:"toolCaptures,omitempty"`
	TraceId      *string        `json:"traceId,omitempty"`
}

// TraceStep defines model for TraceStep.
type TraceStep struct {
	Completion       *string `json:"completion,omitempty"`
	CompletionTokens *int    `json:"completionTokens,omitempty"`
	LatencyMs        *int    `json:"latencyMs,omitempty"`

	// Metadata Arbitrary per-step metadata (e.g. change_context).
	Metadata     *map[string]interface{} `json:"metadata,omitempty"`
	Model        *string                 `json:"model,omitempty"`
	Prompt       *PromptContent          `json:"prompt,omitempty"`
	PromptTokens *int                    `json:"promptTokens,omitempty"`
	Provider     *string                 `json:"provider,omitempty"`
	SpanId       *string                 `json:"spanId,omitempty"`
	StepIndex    *int                    `json:"stepIndex,omitempty"`
}

// TraceSummary defines model for TraceSummary.
type TraceSummary struct {
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	Models    *[]string  `json:"models,omitempty"`
	Providers *[]string  `json:"providers,omitempty"`
	StepCount *int       `json:"stepCount,omitempty"`
	TraceId   *string    `json:"traceId,omitempty"`
}

// VariantConfig defines model for VariantConfig.
type VariantConfig struct {
	MaxTokens      *int                  `json:"maxTokens,omitempty"`
	Model          *string               `json:"model,omitempty"`
	Provider       *string               `json:"provider,omitempty"`
	RequestHeaders *ReplayRequestHeaders `json:"requestHeaders,omitempty"`
	Temperature    *float32              `json:"temperature,omitempty"`
	TopP           *float32              `json:"topP,omitempty"`
}

// Error defines model for Error.
type Error struct {
	Code  *string `json:"code,omitempty"`
	Error string  `json:"error"`
}

// CreateBaselineJSONBody defines parameters for CreateBaseline.
type CreateBaselineJSONBody struct {
	Description *string `json:"description,omitempty"`
	Name        *string `json:"name,omitempty"`
}

// ListDriftResultsParams defines parameters for ListDriftResults.
type ListDriftResultsParams struct {
	Limit  *int `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// GetDriftResultParams defines parameters for GetDriftResult.
type GetDriftResultParams struct {
	BaselineTraceId *string `form:"baselineTraceId,omitempty" json:"baselineTraceId,omitempty"`
}

// ListExperimentsParams defines parameters for ListExperiments.
type ListExperimentsParams struct {
	Status *ListExperimentsParamsStatus `form:"status,omitempty" json:"status,omitempty"`
	Limit  *int                         `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int                         `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListExperimentsParamsStatus defines parameters for ListExperiments.
type ListExperimentsParamsStatus string

// ListTracesParams defines parameters for ListTraces.
type ListTracesParams struct {
	Model    *string `form:"model,omitempty" json:"model,omitempty"`
	Provider *string `form:"provider,omitempty" json:"provider,omitempty"`
	Limit    *int    `form:"limit,omitempty" json:"limit,omitempty"`
	Offset   *int    `form:"offset,omitempty" json:"offset,omitempty"`
}

// CreateBaselineJSONRequestBody defines body for CreateBaseline for application/json ContentType.
type CreateBaselineJSONRequestBody CreateBaselineJSONBody

// CreateGateCheckJSONRequestBody defines body for CreateGateCheck for application/json ContentType.
type CreateGateCheckJSONRequestBody = GateCheckRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List all approved baselines
	// (GET /baselines)
	ListBaselines(w http.ResponseWriter, r *http.Request)
	// Unmark a trace as baseline
	// (DELETE /baselines/{traceId})
	DeleteBaseline(w http.ResponseWriter, r *http.Request, traceId string)
	// Mark a trace as a baseline
	// (POST /baselines/{traceId})
	CreateBaseline(w http.ResponseWriter, r *http.Request, traceId string)
	// Side-by-side trace comparison
	// (GET /compare/{baselineTraceId}/{candidateTraceId})
	CompareTraces(w http.ResponseWriter, r *http.Request, baselineTraceId string, candidateTraceId string)
	// List drift results (Drift Inbox)
	// (GET /drift-results)
	ListDriftResults(w http.ResponseWriter, r *http.Request, params ListDriftResultsParams)
	// Get drift details for a specific trace
	// (GET /drift-results/{traceId})
	GetDriftResult(w http.ResponseWriter, r *http.Request, traceId string, params GetDriftResultParams)
	// List experiments (Gate Runs)
	// (GET /experiments)
	ListExperiments(w http.ResponseWriter, r *http.Request, params ListExperimentsParams)
	// Get experiment details
	// (GET /experiments/{id})
	GetExperiment(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Get canonical experiment report for review
	// (GET /experiments/{id}/report)
	GetExperimentReport(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Start a deployment gate check
	// (POST /gate/check)
	CreateGateCheck(w http.ResponseWriter, r *http.Request)
	// Get status of a gate check
	// (GET /gate/status/{id})
	GetGateStatus(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Health check
	// (GET /health)
	GetHealth(w http.ResponseWriter, r *http.Request)
	// List replayed traces
	// (GET /traces)
	ListTraces(w http.ResponseWriter, r *http.Request, params ListTracesParams)
	// Get trace details (steps)
	// (GET /traces/{traceId})
	GetTrace(w http.ResponseWriter, r *http.Request, traceId string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListBaselines operation middleware
func (siw *ServerInterfaceWrapper) ListBaselines(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListBaselines(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteBaseline operation middleware
func (siw *ServerInterfaceWrapper) DeleteBaseline(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "traceId" -------------
	var traceId string

	err = runtime.BindStyledParameterWithOptions("simple", "traceId", r.PathValue("traceId"), &traceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "traceId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteBaseline(w, r, traceId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateBaseline operation middleware
func (siw *ServerInterfaceWrapper) CreateBaseline(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "traceId" -------------
	var traceId string

	err = runtime.BindStyledParameterWithOptions("simple", "traceId", r.PathValue("traceId"), &traceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "traceId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateBaseline(w, r, traceId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CompareTraces operation middleware
func (siw *ServerInterfaceWrapper) CompareTraces(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "baselineTraceId" -------------
	var baselineTraceId string

	err = runtime.BindStyledParameterWithOptions("simple", "baselineTraceId", r.PathValue("baselineTraceId"), &baselineTraceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "baselineTraceId", Err: err})
		return
	}

	// ------------- Path parameter "candidateTraceId" -------------
	var candidateTraceId string

	err = runtime.BindStyledParameterWithOptions("simple", "candidateTraceId", r.PathValue("candidateTraceId"), &candidateTraceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "candidateTraceId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CompareTraces(w, r, baselineTraceId, candidateTraceId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListDriftResults operation middleware
func (siw *ServerInterfaceWrapper) ListDriftResults(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListDriftResultsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListDriftResults(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetDriftResult operation middleware
func (siw *ServerInterfaceWrapper) GetDriftResult(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "traceId" -------------
	var traceId string

	err = runtime.BindStyledParameterWithOptions("simple", "traceId", r.PathValue("traceId"), &traceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "traceId", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetDriftResultParams

	// ------------- Optional query parameter "baselineTraceId" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "baselineTraceId", r.URL.Query(), &params.BaselineTraceId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "baselineTraceId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDriftResult(w, r, traceId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListExperiments operation middleware
func (siw *ServerInterfaceWrapper) ListExperiments(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListExperimentsParams

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "status", r.URL.Query(), &params.Status, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListExperiments(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetExperiment operation middleware
func (siw *ServerInterfaceWrapper) GetExperiment(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetExperiment(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetExperimentReport operation middleware
func (siw *ServerInterfaceWrapper) GetExperimentReport(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetExperimentReport(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateGateCheck operation middleware
func (siw *ServerInterfaceWrapper) CreateGateCheck(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateGateCheck(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetGateStatus operation middleware
func (siw *ServerInterfaceWrapper) GetGateStatus(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetGateStatus(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListTraces operation middleware
func (siw *ServerInterfaceWrapper) ListTraces(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListTracesParams

	// ------------- Optional query parameter "model" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "model", r.URL.Query(), &params.Model, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "model", Err: err})
		return
	}

	// ------------- Optional query parameter "provider" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "provider", r.URL.Query(), &params.Provider, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "provider", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListTraces(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTrace operation middleware
func (siw *ServerInterfaceWrapper) GetTrace(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "traceId" -------------
	var traceId string

	err = runtime.BindStyledParameterWithOptions("simple", "traceId", r.PathValue("traceId"), &traceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "traceId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTrace(w, r, traceId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/baselines", wrapper.ListBaselines)
	m.HandleFunc("DELETE "+options.BaseURL+"/baselines/{traceId}", wrapper.DeleteBaseline)
	m.HandleFunc("POST "+options.BaseURL+"/baselines/{traceId}", wrapper.CreateBaseline)
	m.HandleFunc("GET "+options.BaseURL+"/compare/{baselineTraceId}/{candidateTraceId}", wrapper.CompareTraces)
	m.HandleFunc("GET "+options.BaseURL+"/drift-results", wrapper.ListDriftResults)
	m.HandleFunc("GET "+options.BaseURL+"/drift-results/{traceId}", wrapper.GetDriftResult)
	m.HandleFunc("GET "+options.BaseURL+"/experiments", wrapper.ListExperiments)
	m.HandleFunc("GET "+options.BaseURL+"/experiments/{id}", wrapper.GetExperiment)
	m.HandleFunc("GET "+options.BaseURL+"/experiments/{id}/report", wrapper.GetExperimentReport)
	m.HandleFunc("POST "+options.BaseURL+"/gate/check", wrapper.CreateGateCheck)
	m.HandleFunc("GET "+options.BaseURL+"/gate/status/{id}", wrapper.GetGateStatus)
	m.HandleFunc("GET "+options.BaseURL+"/health", wrapper.GetHealth)
	m.HandleFunc("GET "+options.BaseURL+"/traces", wrapper.ListTraces)
	m.HandleFunc("GET "+options.BaseURL+"/traces/{traceId}", wrapper.GetTrace)

	return m
}
