// Package apiclient provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package apiclient

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for DriftResultVerdict.
const (
	DriftResultVerdictFail    DriftResultVerdict = "fail"
	DriftResultVerdictPass    DriftResultVerdict = "pass"
	DriftResultVerdictPending DriftResultVerdict = "pending"
	DriftResultVerdictWarn    DriftResultVerdict = "warn"
)

// Valid indicates whether the value is a known member of the DriftResultVerdict enum.
func (e DriftResultVerdict) Valid() bool {
	switch e {
	case DriftResultVerdictFail:
		return true
	case DriftResultVerdictPass:
		return true
	case DriftResultVerdictPending:
		return true
	case DriftResultVerdictWarn:
		return true
	default:
		return false
	}
}

// Defines values for ExperimentRunRunType.
const (
	ExperimentRunRunTypeBaseline ExperimentRunRunType = "baseline"
	ExperimentRunRunTypeVariant  ExperimentRunRunType = "variant"
)

// Valid indicates whether the value is a known member of the ExperimentRunRunType enum.
func (e ExperimentRunRunType) Valid() bool {
	switch e {
	case ExperimentRunRunTypeBaseline:
		return true
	case ExperimentRunRunTypeVariant:
		return true
	default:
		return false
	}
}

// Defines values for ToolCaptureRiskClass.
const (
	Destructive ToolCaptureRiskClass = "destructive"
	Read        ToolCaptureRiskClass = "read"
	Write       ToolCaptureRiskClass = "write"
)

// Valid indicates whether the value is a known member of the ToolCaptureRiskClass enum.
func (e ToolCaptureRiskClass) Valid() bool {
	switch e {
	case Destructive:
		return true
	case Read:
		return true
	case Write:
		return true
	default:
		return false
	}
}

// Defines values for ListExperimentsParamsStatus.
const (
	ListExperimentsParamsStatusCancelled ListExperimentsParamsStatus = "cancelled"
	ListExperimentsParamsStatusCompleted ListExperimentsParamsStatus = "completed"
	ListExperimentsParamsStatusFailed    ListExperimentsParamsStatus = "failed"
	ListExperimentsParamsStatusPending   ListExperimentsParamsStatus = "pending"
	ListExperimentsParamsStatusRunning   ListExperimentsParamsStatus = "running"
)

// Valid indicates whether the value is a known member of the ListExperimentsParamsStatus enum.
func (e ListExperimentsParamsStatus) Valid() bool {
	switch e {
	case ListExperimentsParamsStatusCancelled:
		return true
	case ListExperimentsParamsStatusCompleted:
		return true
	case ListExperimentsParamsStatusFailed:
		return true
	case ListExperimentsParamsStatusPending:
		return true
	case ListExperimentsParamsStatusRunning:
		return true
	default:
		return false
	}
}

// AnalysisResult defines model for AnalysisResult.
type AnalysisResult struct {
	BehaviorDiff    *BehaviorDiff    `json:"behaviorDiff,omitempty"`
	FirstDivergence *FirstDivergence `json:"firstDivergence,omitempty"`
	SafetyDiff      *SafetyDiff      `json:"safetyDiff,omitempty"`
}

// Baseline defines model for Baseline.
type Baseline struct {
	CreatedAt   *time.Time `json:"createdAt,omitempty"`
	Description *string    `json:"description,omitempty"`
	Name        *string    `json:"name,omitempty"`
	TraceId     *string    `json:"traceId,omitempty"`
}

// BehaviorDiff defines model for BehaviorDiff.
type BehaviorDiff struct {
	Reason  *string `json:"reason,omitempty"`
	Verdict *string `json:"verdict,omitempty"`
}

// DriftDetails defines model for DriftDetails.
type DriftDetails struct {
	DivergenceStep *int    `json:"divergenceStep,omitempty"`
	Reason         *string `json:"reason,omitempty"`
	RiskEscalation *bool   `json:"riskEscalation,omitempty"`
}

// DriftResult defines model for DriftResult.
type DriftResult struct {
	BaselineTraceId *string             `json:"baselineTraceId,omitempty"`
	CreatedAt       *time.Time          `json:"createdAt,omitempty"`
	Details         *DriftDetails       `json:"details,omitempty"`
	DriftScore      *float32            `json:"driftScore,omitempty"`
	TraceId         *string             `json:"traceId,omitempty"`
	Verdict         *DriftResultVerdict `json:"verdict,omitempty"`
}

// DriftResultVerdict defines model for DriftResult.Verdict.
type DriftResultVerdict string

// Experiment defines model for Experiment.
type Experiment struct {
	BaselineTraceId *string             `json:"baselineTraceId,omitempty"`
	CompletedAt     *time.Time          `json:"completedAt,omitempty"`
	CreatedAt       *time.Time          `json:"createdAt,omitempty"`
	Id              *openapi_types.UUID `json:"id,omitempty"`
	Name            *string             `json:"name,omitempty"`
	Progress        *float32            `json:"progress,omitempty"`
	Status          *string             `json:"status,omitempty"`
	Threshold       *float32            `json:"threshold,omitempty"`
	VariantConfig   *VariantConfig      `json:"variantConfig,omitempty"`
	Verdict         *string             `json:"verdict,omitempty"`
}

// ExperimentDetail defines model for ExperimentDetail.
type ExperimentDetail struct {
	BaselineTraceId *string             `json:"baselineTraceId,omitempty"`
	CompletedAt     *time.Time          `json:"completedAt,omitempty"`
	CreatedAt       *time.Time          `json:"createdAt,omitempty"`
	Id              *openapi_types.UUID `json:"id,omitempty"`
	Name            *string             `json:"name,omitempty"`
	Progress        *float32            `json:"progress,omitempty"`
	Runs            *[]ExperimentRun    `json:"runs,omitempty"`
	Status          *string             `json:"status,omitempty"`
	Threshold       *float32            `json:"threshold,omitempty"`
	VariantConfig   *VariantConfig      `json:"variantConfig,omitempty"`
	Verdict         *string             `json:"verdict,omitempty"`
}

// ExperimentReport defines model for ExperimentReport.
type ExperimentReport struct {
	Analysis        *AnalysisResult     `json:"analysis,omitempty"`
	BaselineTraceId *string             `json:"baselineTraceId,omitempty"`
	Error           *string             `json:"error,omitempty"`
	ExperimentId    *openapi_types.UUID `json:"experimentId,omitempty"`
	LatencyDelta    *int                `json:"latencyDelta,omitempty"`
	Runs            *[]ExperimentRun    `json:"runs,omitempty"`
	SimilarityScore *float32            `json:"similarityScore,omitempty"`
	Status          *string             `json:"status,omitempty"`
	TokenDelta      *int                `json:"tokenDelta,omitempty"`
	Verdict         *string             `json:"verdict,omitempty"`
}

// ExperimentRun defines model for ExperimentRun.
type ExperimentRun struct {
	CreatedAt     *time.Time            `json:"createdAt,omitempty"`
	Error         *string               `json:"error,omitempty"`
	Id            *openapi_types.UUID   `json:"id,omitempty"`
	RunType       *ExperimentRunRunType `json:"runType,omitempty"`
	Status        *string               `json:"status,omitempty"`
	TraceId       *string               `json:"traceId,omitempty"`
	VariantConfig *VariantConfig        `json:"variantConfig,omitempty"`
}

// ExperimentRunRunType defines model for ExperimentRun.RunType.
type ExperimentRunRunType string

// FirstDivergence defines model for FirstDivergence.
type FirstDivergence struct {
	Baseline        *string `json:"baseline,omitempty"`
	BaselineCount   *int    `json:"baselineCount,omitempty"`
	BaselineExcerpt *string `json:"baselineExcerpt,omitempty"`
	BaselineSteps   *int    `json:"baselineSteps,omitempty"`
	StepIndex       *int    `json:"stepIndex,omitempty"`
	ToolIndex       *int    `json:"toolIndex,omitempty"`
	Type            *string `json:"type,omitempty"`
	Variant         *string `json:"variant,omitempty"`
	VariantCount    *int    `json:"variantCount,omitempty"`
	VariantExcerpt  *string `json:"variantExcerpt,omitempty"`
	VariantSteps    *int    `json:"variantSteps,omitempty"`
}

// GateCheckRequest defines model for GateCheckRequest.
type GateCheckRequest struct {
	BaselineTraceId string `json:"baselineTraceId"`
	MaxTokens       *int   `json:"maxTokens,omitempty"`

	// MaxTurns Maximum agent loop turns (overrides server default)
	MaxTurns       *int                  `json:"maxTurns,omitempty"`
	Model          string                `json:"model"`
	Provider       *string               `json:"provider,omitempty"`
	RequestHeaders *ReplayRequestHeaders `json:"requestHeaders,omitempty"`
	Temperature    *float32              `json:"temperature,omitempty"`
	Threshold      *float32              `json:"threshold,omitempty"`
	TopP           *float32              `json:"topP,omitempty"`
}

// GateCheckResponse defines model for GateCheckResponse.
type GateCheckResponse struct {
	ExperimentId *openapi_types.UUID `json:"experimentId,omitempty"`
	Status       *string             `json:"status,omitempty"`
}

// GateStatusResponse defines model for GateStatusResponse.
type GateStatusResponse struct {
	ExperimentId *openapi_types.UUID `json:"experimentId,omitempty"`
	Progress     *float32            `json:"progress,omitempty"`
	Status       *string             `json:"status,omitempty"`
}

// PromptContent defines model for PromptContent.
type PromptContent struct {
	Messages *[]PromptMessage `json:"messages,omitempty"`

	// ToolChoice Arbitrary tool-choice payload captured from the source trace.
	ToolChoice interface{}               `json:"tool_choice,omitempty"`
	Tools      *[]map[string]interface{} `json:"tools,omitempty"`
}

// PromptMessage defines model for PromptMessage.
type PromptMessage struct {
	Content    *string                   `json:"content,omitempty"`
	Name       *string                   `json:"name,omitempty"`
	Role       *string                   `json:"role,omitempty"`
	ToolCallId *string                   `json:"tool_call_id,omitempty"`
	ToolCalls  *[]map[string]interface{} `json:"tool_calls,omitempty"`
}

// ReplayRequestHeaders defines model for ReplayRequestHeaders.
type ReplayRequestHeaders struct {
	FreezeSpanId    *string `json:"freezeSpanId,omitempty"`
	FreezeStepIndex *string `json:"freezeStepIndex,omitempty"`
	FreezeTraceId   *string `json:"freezeTraceId,omitempty"`
}

// SafetyDiff defines model for SafetyDiff.
type SafetyDiff struct {
	BaselineRisk   *string `json:"baselineRisk,omitempty"`
	RiskEscalation *bool   `json:"riskEscalation,omitempty"`
	VariantRisk    *string `json:"variantRisk,omitempty"`
}

// ToolCapture defines model for ToolCapture.
type ToolCapture struct {
	Args      *map[string]interface{} `json:"args,omitempty"`
	Error     *string                 `json:"error,omitempty"`
	LatencyMs *int                    `json:"latencyMs,omitempty"`
	Result    *map[string]interface{} `json:"result,omitempty"`
	RiskClass *ToolCaptureRiskClass   `json:"riskClass,omitempty"`
	StepIndex *int                    `json:"stepIndex,omitempty"`
	ToolName  *string                 `json:"toolName,omitempty"`
}

// ToolCaptureRiskClass defines model for ToolCapture.RiskClass.
type ToolCaptureRiskClass string

// TraceComparison defines model for TraceComparison.
type TraceComparison struct {
	Baseline  *TraceDetail `json:"baseline,omitempty"`
	Candidate *TraceDetail `json:"candidate,omitempty"`
	Diff      *struct {
		DivergenceReason    *string  `json:"divergenceReason,omitempty"`
		DivergenceStepIndex *int     `json:"divergenceStepIndex,omitempty"`
		SimilarityScore     *float32 `json:"similarityScore,omitempty"`
	} `json:"diff,omitempty"`
}

// TraceDetail defines model for TraceDetail.
type TraceDetail struct {
	Steps        *[]TraceStep   `json:"steps,omitempty"`
	ToolCaptures *[]ToolCapture `json:"toolCaptures,omitempty"`
	TraceId      *string        `json:"traceId,omitempty"`
}

// TraceStep defines model for TraceStep.
type TraceStep struct {
	Completion       *string `json:"completion,omitempty"`
	CompletionTokens *int    `json:"completionTokens,omitempty"`
	LatencyMs        *int    `json:"latencyMs,omitempty"`

	// Metadata Arbitrary per-step metadata (e.g. change_context).
	Metadata     *map[string]interface{} `json:"metadata,omitempty"`
	Model        *string                 `json:"model,omitempty"`
	Prompt       *PromptContent          `json:"prompt,omitempty"`
	PromptTokens *int                    `json:"promptTokens,omitempty"`
	Provider     *string                 `json:"provider,omitempty"`
	SpanId       *string                 `json:"spanId,omitempty"`
	StepIndex    *int                    `json:"stepIndex,omitempty"`
}

// TraceSummary defines model for TraceSummary.
type TraceSummary struct {
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	Models    *[]string  `json:"models,omitempty"`
	Providers *[]string  `json:"providers,omitempty"`
	StepCount *int       `json:"stepCount,omitempty"`
	TraceId   *string    `json:"traceId,omitempty"`
}

// VariantConfig defines model for VariantConfig.
type VariantConfig struct {
	MaxTokens      *int                  `json:"maxTokens,omitempty"`
	Model          *string               `json:"model,omitempty"`
	Provider       *string               `json:"provider,omitempty"`
	RequestHeaders *ReplayRequestHeaders `json:"requestHeaders,omitempty"`
	Temperature    *float32              `json:"temperature,omitempty"`
	TopP           *float32              `json:"topP,omitempty"`
}

// Error defines model for Error.
type Error struct {
	Code  *string `json:"code,omitempty"`
	Error string  `json:"error"`
}

// CreateBaselineJSONBody defines parameters for CreateBaseline.
type CreateBaselineJSONBody struct {
	Description *string `json:"description,omitempty"`
	Name        *string `json:"name,omitempty"`
}

// ListDriftResultsParams defines parameters for ListDriftResults.
type ListDriftResultsParams struct {
	Limit  *int `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// GetDriftResultParams defines parameters for GetDriftResult.
type GetDriftResultParams struct {
	BaselineTraceId *string `form:"baselineTraceId,omitempty" json:"baselineTraceId,omitempty"`
}

// ListExperimentsParams defines parameters for ListExperiments.
type ListExperimentsParams struct {
	Status *ListExperimentsParamsStatus `form:"status,omitempty" json:"status,omitempty"`
	Limit  *int                         `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int                         `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListExperimentsParamsStatus defines parameters for ListExperiments.
type ListExperimentsParamsStatus string

// ListTracesParams defines parameters for ListTraces.
type ListTracesParams struct {
	Model    *string `form:"model,omitempty" json:"model,omitempty"`
	Provider *string `form:"provider,omitempty" json:"provider,omitempty"`
	Limit    *int    `form:"limit,omitempty" json:"limit,omitempty"`
	Offset   *int    `form:"offset,omitempty" json:"offset,omitempty"`
}

// CreateBaselineJSONRequestBody defines body for CreateBaseline for application/json ContentType.
type CreateBaselineJSONRequestBody CreateBaselineJSONBody

// CreateGateCheckJSONRequestBody defines body for CreateGateCheck for application/json ContentType.
type CreateGateCheckJSONRequestBody = GateCheckRequest

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// ListBaselines request
	ListBaselines(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteBaseline request
	DeleteBaseline(ctx context.Context, traceId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateBaselineWithBody request with any body
	CreateBaselineWithBody(ctx context.Context, traceId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateBaseline(ctx context.Context, traceId string, body CreateBaselineJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CompareTraces request
	CompareTraces(ctx context.Context, baselineTraceId string, candidateTraceId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListDriftResults request
	ListDriftResults(ctx context.Context, params *ListDriftResultsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetDriftResult request
	GetDriftResult(ctx context.Context, traceId string, params *GetDriftResultParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListExperiments request
	ListExperiments(ctx context.Context, params *ListExperimentsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetExperiment request
	GetExperiment(ctx context.Context, id openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetExperimentReport request
	GetExperimentReport(ctx context.Context, id openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateGateCheckWithBody request with any body
	CreateGateCheckWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateGateCheck(ctx context.Context, body CreateGateCheckJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetGateStatus request
	GetGateStatus(ctx context.Context, id openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetHealth request
	GetHealth(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListTraces request
	ListTraces(ctx context.Context, params *ListTracesParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetTrace request
	GetTrace(ctx context.Context, traceId string, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) ListBaselines(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListBaselinesRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteBaseline(ctx context.Context, traceId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteBaselineRequest(c.Server, traceId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateBaselineWithBody(ctx context.Context, traceId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateBaselineRequestWithBody(c.Server, traceId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateBaseline(ctx context.Context, traceId string, body CreateBaselineJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateBaselineRequest(c.Server, traceId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CompareTraces(ctx context.Context, baselineTraceId string, candidateTraceId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCompareTracesRequest(c.Server, baselineTraceId, candidateTraceId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListDriftResults(ctx context.Context, params *ListDriftResultsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListDriftResultsRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetDriftResult(ctx context.Context, traceId string, params *GetDriftResultParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetDriftResultRequest(c.Server, traceId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListExperiments(ctx context.Context, params *ListExperimentsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListExperimentsRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetExperiment(ctx context.Context, id openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetExperimentRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetExperimentReport(ctx context.Context, id openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetExperimentReportRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateGateCheckWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateGateCheckRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateGateCheck(ctx context.Context, body CreateGateCheckJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateGateCheckRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetGateStatus(ctx context.Context, id openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetGateStatusRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetHealth(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetHealthRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListTraces(ctx context.Context, params *ListTracesParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListTracesRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetTrace(ctx context.Context, traceId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetTraceRequest(c.Server, traceId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewListBaselinesRequest generates requests for ListBaselines
func NewListBaselinesRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/baselines")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewDeleteBaselineRequest generates requests for DeleteBaseline
func NewDeleteBaselineRequest(server string, traceId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "traceId", traceId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/baselines/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCreateBaselineRequest calls the generic CreateBaseline builder with application/json body
func NewCreateBaselineRequest(server string, traceId string, body CreateBaselineJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateBaselineRequestWithBody(server, traceId, "application/json", bodyReader)
}

// NewCreateBaselineRequestWithBody generates requests for CreateBaseline with any type of body
func NewCreateBaselineRequestWithBody(server string, traceId string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "traceId", traceId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/baselines/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewCompareTracesRequest generates requests for CompareTraces
func NewCompareTracesRequest(server string, baselineTraceId string, candidateTraceId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "baselineTraceId", baselineTraceId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "candidateTraceId", candidateTraceId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/compare/%s/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewListDriftResultsRequest generates requests for ListDriftResults
func NewListDriftResultsRequest(server string, params *ListDriftResultsParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/drift-results")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "limit", *params.Limit, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Offset != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "offset", *params.Offset, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetDriftResultRequest generates requests for GetDriftResult
func NewGetDriftResultRequest(server string, traceId string, params *GetDriftResultParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "traceId", traceId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/drift-results/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.BaselineTraceId != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "baselineTraceId", *params.BaselineTraceId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewListExperimentsRequest generates requests for ListExperiments
func NewListExperimentsRequest(server string, params *ListExperimentsParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/experiments")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Status != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "status", *params.Status, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "limit", *params.Limit, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Offset != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "offset", *params.Offset, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetExperimentRequest generates requests for GetExperiment
func NewGetExperimentRequest(server string, id openapi_types.UUID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/experiments/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetExperimentReportRequest generates requests for GetExperimentReport
func NewGetExperimentReportRequest(server string, id openapi_types.UUID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/experiments/%s/report", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCreateGateCheckRequest calls the generic CreateGateCheck builder with application/json body
func NewCreateGateCheckRequest(server string, body CreateGateCheckJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateGateCheckRequestWithBody(server, "application/json", bodyReader)
}

// NewCreateGateCheckRequestWithBody generates requests for CreateGateCheck with any type of body
func NewCreateGateCheckRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/gate/check")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetGateStatusRequest generates requests for GetGateStatus
func NewGetGateStatusRequest(server string, id openapi_types.UUID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/gate/status/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetHealthRequest generates requests for GetHealth
func NewGetHealthRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/health")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewListTracesRequest generates requests for ListTraces
func NewListTracesRequest(server string, params *ListTracesParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/traces")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Model != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "model", *params.Model, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Provider != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "provider", *params.Provider, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "limit", *params.Limit, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Offset != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "offset", *params.Offset, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetTraceRequest generates requests for GetTrace
func NewGetTraceRequest(server string, traceId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "traceId", traceId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/traces/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// ListBaselinesWithResponse request
	ListBaselinesWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListBaselinesResp, error)

	// DeleteBaselineWithResponse request
	DeleteBaselineWithResponse(ctx context.Context, traceId string, reqEditors ...RequestEditorFn) (*DeleteBaselineResp, error)

	// CreateBaselineWithBodyWithResponse request with any body
	CreateBaselineWithBodyWithResponse(ctx context.Context, traceId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateBaselineResp, error)

	CreateBaselineWithResponse(ctx context.Context, traceId string, body CreateBaselineJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateBaselineResp, error)

	// CompareTracesWithResponse request
	CompareTracesWithResponse(ctx context.Context, baselineTraceId string, candidateTraceId string, reqEditors ...RequestEditorFn) (*CompareTracesResp, error)

	// ListDriftResultsWithResponse request
	ListDriftResultsWithResponse(ctx context.Context, params *ListDriftResultsParams, reqEditors ...RequestEditorFn) (*ListDriftResultsResp, error)

	// GetDriftResultWithResponse request
	GetDriftResultWithResponse(ctx context.Context, traceId string, params *GetDriftResultParams, reqEditors ...RequestEditorFn) (*GetDriftResultResp, error)

	// ListExperimentsWithResponse request
	ListExperimentsWithResponse(ctx context.Context, params *ListExperimentsParams, reqEditors ...RequestEditorFn) (*ListExperimentsResp, error)

	// GetExperimentWithResponse request
	GetExperimentWithResponse(ctx context.Context, id openapi_types.UUID, reqEditors ...RequestEditorFn) (*GetExperimentResp, error)

	// GetExperimentReportWithResponse request
	GetExperimentReportWithResponse(ctx context.Context, id openapi_types.UUID, reqEditors ...RequestEditorFn) (*GetExperimentReportResp, error)

	// CreateGateCheckWithBodyWithResponse request with any body
	CreateGateCheckWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateGateCheckResp, error)

	CreateGateCheckWithResponse(ctx context.Context, body CreateGateCheckJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateGateCheckResp, error)

	// GetGateStatusWithResponse request
	GetGateStatusWithResponse(ctx context.Context, id openapi_types.UUID, reqEditors ...RequestEditorFn) (*GetGateStatusResp, error)

	// GetHealthWithResponse request
	GetHealthWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetHealthResp, error)

	// ListTracesWithResponse request
	ListTracesWithResponse(ctx context.Context, params *ListTracesParams, reqEditors ...RequestEditorFn) (*ListTracesResp, error)

	// GetTraceWithResponse request
	GetTraceWithResponse(ctx context.Context, traceId string, reqEditors ...RequestEditorFn) (*GetTraceResp, error)
}

type ListBaselinesResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]Baseline
	JSON500      *Error
}

// Status returns HTTPResponse.Status
func (r ListBaselinesResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListBaselinesResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DeleteBaselineResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON404      *Error
	JSON500      *Error
}

// Status returns HTTPResponse.Status
func (r DeleteBaselineResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteBaselineResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CreateBaselineResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *Baseline
	JSON400      *Error
	JSON404      *Error
	JSON500      *Error
}

// Status returns HTTPResponse.Status
func (r CreateBaselineResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateBaselineResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CompareTracesResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *TraceComparison
	JSON404      *Error
	JSON500      *Error
}

// Status returns HTTPResponse.Status
func (r CompareTracesResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CompareTracesResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ListDriftResultsResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]DriftResult
	JSON500      *Error
}

// Status returns HTTPResponse.Status
func (r ListDriftResultsResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListDriftResultsResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetDriftResultResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *DriftResult
	JSON400      *Error
	JSON404      *Error
	JSON500      *Error
}

// Status returns HTTPResponse.Status
func (r GetDriftResultResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetDriftResultResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ListExperimentsResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]Experiment
	JSON500      *Error
}

// Status returns HTTPResponse.Status
func (r ListExperimentsResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListExperimentsResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetExperimentResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ExperimentDetail
	JSON404      *Error
	JSON500      *Error
}

// Status returns HTTPResponse.Status
func (r GetExperimentResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetExperimentResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetExperimentReportResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ExperimentReport
	JSON404      *Error
	JSON500      *Error
}

// Status returns HTTPResponse.Status
func (r GetExperimentReportResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetExperimentReportResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CreateGateCheckResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON202      *GateCheckResponse
	JSON400      *Error
	JSON404      *Error
	JSON500      *Error
	JSON503      *Error
}

// Status returns HTTPResponse.Status
func (r CreateGateCheckResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateGateCheckResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetGateStatusResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *GateStatusResponse
	JSON404      *Error
	JSON500      *Error
}

// Status returns HTTPResponse.Status
func (r GetGateStatusResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetGateStatusResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetHealthResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Status *GetHealth200Status `json:"status,omitempty"`
	}
}
type GetHealth200Status string

// Status returns HTTPResponse.Status
func (r GetHealthResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetHealthResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ListTracesResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]TraceSummary
	JSON500      *Error
}

// Status returns HTTPResponse.Status
func (r ListTracesResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListTracesResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetTraceResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *TraceDetail
	JSON404      *Error
	JSON500      *Error
}

// Status returns HTTPResponse.Status
func (r GetTraceResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetTraceResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ListBaselinesWithResponse request returning *ListBaselinesResp
func (c *ClientWithResponses) ListBaselinesWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListBaselinesResp, error) {
	rsp, err := c.ListBaselines(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListBaselinesResp(rsp)
}

// DeleteBaselineWithResponse request returning *DeleteBaselineResp
func (c *ClientWithResponses) DeleteBaselineWithResponse(ctx context.Context, traceId string, reqEditors ...RequestEditorFn) (*DeleteBaselineResp, error) {
	rsp, err := c.DeleteBaseline(ctx, traceId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteBaselineResp(rsp)
}

// CreateBaselineWithBodyWithResponse request with arbitrary body returning *CreateBaselineResp
func (c *ClientWithResponses) CreateBaselineWithBodyWithResponse(ctx context.Context, traceId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateBaselineResp, error) {
	rsp, err := c.CreateBaselineWithBody(ctx, traceId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateBaselineResp(rsp)
}

func (c *ClientWithResponses) CreateBaselineWithResponse(ctx context.Context, traceId string, body CreateBaselineJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateBaselineResp, error) {
	rsp, err := c.CreateBaseline(ctx, traceId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateBaselineResp(rsp)
}

// CompareTracesWithResponse request returning *CompareTracesResp
func (c *ClientWithResponses) CompareTracesWithResponse(ctx context.Context, baselineTraceId string, candidateTraceId string, reqEditors ...RequestEditorFn) (*CompareTracesResp, error) {
	rsp, err := c.CompareTraces(ctx, baselineTraceId, candidateTraceId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCompareTracesResp(rsp)
}

// ListDriftResultsWithResponse request returning *ListDriftResultsResp
func (c *ClientWithResponses) ListDriftResultsWithResponse(ctx context.Context, params *ListDriftResultsParams, reqEditors ...RequestEditorFn) (*ListDriftResultsResp, error) {
	rsp, err := c.ListDriftResults(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListDriftResultsResp(rsp)
}

// GetDriftResultWithResponse request returning *GetDriftResultResp
func (c *ClientWithResponses) GetDriftResultWithResponse(ctx context.Context, traceId string, params *GetDriftResultParams, reqEditors ...RequestEditorFn) (*GetDriftResultResp, error) {
	rsp, err := c.GetDriftResult(ctx, traceId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetDriftResultResp(rsp)
}

// ListExperimentsWithResponse request returning *ListExperimentsResp
func (c *ClientWithResponses) ListExperimentsWithResponse(ctx context.Context, params *ListExperimentsParams, reqEditors ...RequestEditorFn) (*ListExperimentsResp, error) {
	rsp, err := c.ListExperiments(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListExperimentsResp(rsp)
}

// GetExperimentWithResponse request returning *GetExperimentResp
func (c *ClientWithResponses) GetExperimentWithResponse(ctx context.Context, id openapi_types.UUID, reqEditors ...RequestEditorFn) (*GetExperimentResp, error) {
	rsp, err := c.GetExperiment(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetExperimentResp(rsp)
}

// GetExperimentReportWithResponse request returning *GetExperimentReportResp
func (c *ClientWithResponses) GetExperimentReportWithResponse(ctx context.Context, id openapi_types.UUID, reqEditors ...RequestEditorFn) (*GetExperimentReportResp, error) {
	rsp, err := c.GetExperimentReport(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetExperimentReportResp(rsp)
}

// CreateGateCheckWithBodyWithResponse request with arbitrary body returning *CreateGateCheckResp
func (c *ClientWithResponses) CreateGateCheckWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateGateCheckResp, error) {
	rsp, err := c.CreateGateCheckWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateGateCheckResp(rsp)
}

func (c *ClientWithResponses) CreateGateCheckWithResponse(ctx context.Context, body CreateGateCheckJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateGateCheckResp, error) {
	rsp, err := c.CreateGateCheck(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateGateCheckResp(rsp)
}

// GetGateStatusWithResponse request returning *GetGateStatusResp
func (c *ClientWithResponses) GetGateStatusWithResponse(ctx context.Context, id openapi_types.UUID, reqEditors ...RequestEditorFn) (*GetGateStatusResp, error) {
	rsp, err := c.GetGateStatus(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetGateStatusResp(rsp)
}

// GetHealthWithResponse request returning *GetHealthResp
func (c *ClientWithResponses) GetHealthWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetHealthResp, error) {
	rsp, err := c.GetHealth(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetHealthResp(rsp)
}

// ListTracesWithResponse request returning *ListTracesResp
func (c *ClientWithResponses) ListTracesWithResponse(ctx context.Context, params *ListTracesParams, reqEditors ...RequestEditorFn) (*ListTracesResp, error) {
	rsp, err := c.ListTraces(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListTracesResp(rsp)
}

// GetTraceWithResponse request returning *GetTraceResp
func (c *ClientWithResponses) GetTraceWithResponse(ctx context.Context, traceId string, reqEditors ...RequestEditorFn) (*GetTraceResp, error) {
	rsp, err := c.GetTrace(ctx, traceId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetTraceResp(rsp)
}

// ParseListBaselinesResp parses an HTTP response from a ListBaselinesWithResponse call
func ParseListBaselinesResp(rsp *http.Response) (*ListBaselinesResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListBaselinesResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []Baseline
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseDeleteBaselineResp parses an HTTP response from a DeleteBaselineWithResponse call
func ParseDeleteBaselineResp(rsp *http.Response) (*DeleteBaselineResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteBaselineResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseCreateBaselineResp parses an HTTP response from a CreateBaselineWithResponse call
func ParseCreateBaselineResp(rsp *http.Response) (*CreateBaselineResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateBaselineResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest Baseline
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseCompareTracesResp parses an HTTP response from a CompareTracesWithResponse call
func ParseCompareTracesResp(rsp *http.Response) (*CompareTracesResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CompareTracesResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest TraceComparison
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseListDriftResultsResp parses an HTTP response from a ListDriftResultsWithResponse call
func ParseListDriftResultsResp(rsp *http.Response) (*ListDriftResultsResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListDriftResultsResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []DriftResult
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetDriftResultResp parses an HTTP response from a GetDriftResultWithResponse call
func ParseGetDriftResultResp(rsp *http.Response) (*GetDriftResultResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetDriftResultResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest DriftResult
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseListExperimentsResp parses an HTTP response from a ListExperimentsWithResponse call
func ParseListExperimentsResp(rsp *http.Response) (*ListExperimentsResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListExperimentsResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []Experiment
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetExperimentResp parses an HTTP response from a GetExperimentWithResponse call
func ParseGetExperimentResp(rsp *http.Response) (*GetExperimentResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetExperimentResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ExperimentDetail
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetExperimentReportResp parses an HTTP response from a GetExperimentReportWithResponse call
func ParseGetExperimentReportResp(rsp *http.Response) (*GetExperimentReportResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetExperimentReportResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ExperimentReport
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseCreateGateCheckResp parses an HTTP response from a CreateGateCheckWithResponse call
func ParseCreateGateCheckResp(rsp *http.Response) (*CreateGateCheckResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateGateCheckResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 202:
		var dest GateCheckResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON202 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 503:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON503 = &dest

	}

	return response, nil
}

// ParseGetGateStatusResp parses an HTTP response from a GetGateStatusWithResponse call
func ParseGetGateStatusResp(rsp *http.Response) (*GetGateStatusResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetGateStatusResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest GateStatusResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetHealthResp parses an HTTP response from a GetHealthWithResponse call
func ParseGetHealthResp(rsp *http.Response) (*GetHealthResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetHealthResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Status *GetHealth200Status `json:"status,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseListTracesResp parses an HTTP response from a ListTracesWithResponse call
func ParseListTracesResp(rsp *http.Response) (*ListTracesResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListTracesResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []TraceSummary
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetTraceResp parses an HTTP response from a GetTraceWithResponse call
func ParseGetTraceResp(rsp *http.Response) (*GetTraceResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetTraceResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest TraceDetail
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}
